# Generated by Django 5.2.7 on 2025-10-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('tecnologias', models.CharField(blank=True, max_length=250)),
                ('order', models.PositiveIntegerField(default=0, help_text='Para reordenar manualmente')),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
