# Generated by Django 5.2.7 on 2025-10-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_cv', '0002_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='tecnologias',
        ),
        migrations.AddField(
            model_name='experience',
            name='company_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='technologies',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Para reordenar manualmente (0 arriba).'),
        ),
    ]
