# Generated by Django 5.1.6 on 2025-11-22 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_cv', '0003_remove_experience_tecnologias_experience_company_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio_cv.project'),
        ),
    ]
