# Generated by Django 5.1.6 on 2025-11-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_cv', '0004_alter_projectimage_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='company_logo',
        ),
        migrations.AddField(
            model_name='experience',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL del GIF animado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover',
            field=models.URLField(blank=True, help_text='URL del GIF animado'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.URLField(blank=True, help_text='URL del GIF animado'),
        ),
    ]
